todos/main/urls.py
from django.urls import path
from main import views


urlpatterns=[
        # path('', views.homePageView,name='home'),
        path('', views.HomePageListView.as_view(),name='home'),
        path('contact/', views.contactPageView, name='contact'),
        # path('detail/<todo_id>/', views.todo_detailPageView, name='detail'),
        path('detail/<pk>', views.TodoDetailView.as_view(), name='detail'),
        # path('todo/',views.todo_createPageView,name='todo' ),
        # path('update/<todo_id>', views.todo_updatePageView,name='update'),
        path('update/<pk>', views.TodoUpdateView.as_view(),name='update'),
        path('todo/', views.TodoCreateView.as_view(), name='todo')
    ]

todos/todos/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
 ]

todos/main/models.py
from django.db import models

# Create your models here.



class Todo(models.Model):
    title = models.CharField(max_length=200)
    due_date = models.DateField()
    description = models.TextField(blank=True)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todos/main/forms.py
from django import forms
from main.models import Todo
from datetime import date

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = "__all__"

    def clean_title(self):
        title = self.cleaned_data['title']
        words = title.split(' ')
        if len(words) > 5:
            raise forms.ValidationError('Title must be less than or equal to five')
        return title

    def clean_due_date(self):
        due_date = self.cleaned_data['due_date']
        if due_date < date.today():
            raise forms.ValidationError('due date must not be in the past')
        return due_date

todos/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from datetime import datetime
from main.models import Todo
from main.forms import TodoForm
from django.contrib import messages
from django.views.generic import CreateView,UpdateView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin


# Create your views here.
class HomePageListView(ListView):
    queryset = Todo.objects.all()
    template_name = 'main/home.html'
    context_object_name = 'todos'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['today'] = datetime.now()
        ctx['app_name'] = 'Wobble Todos'
        return ctx



def homePageView(request):
    todos = Todo.objects.all()
    context = {'today':datetime.now(), 'app_name':'Wobble Todos','todos':todos}

    return render(request, 'main/home.html',context)

def contactPageView(request):
    return render(request, 'main/contact.html')

class TodoDetailView(DetailView):
    model = Todo
    template_name = 'main/detail.html'

def todo_detailPageView(request, todo_id):
    todo = get_object_or_404(Todo,pk=todo_id)
    context = {'todo':todo }
    return render(request,'main/detail.html',context)

class TodoCreateView(SuccessMessageMixin,CreateView):
    model = Todo
    form_class = TodoForm
    template_name = 'main/todo.html'
    success_url = reverse_lazy('home')
    success_message = 'Todo created successfully!'


def todo_createPageView(request):
    if request.method == 'POST':
        todo = TodoForm(request.POST)
        if todo.is_valid():
            todo.save()
            messages.success(request, 'the todo messages was created successfully')
            return redirect('home')
        return render(request, 'main/todo.html', {"form":todo})
    return render(request, 'main/todo.html', {'form':TodoForm()})

class TodoUpdateView(SuccessMessageMixin,UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = 'main/todo.html'
    success_url = reverse_lazy('home')
    success_message = 'Todo updated successfully!'




def todo_updatePageView(request, todo_id):
    todo = get_object_or_404(Todo,pk=todo_id)
    if request.method == 'POST':
        todo = TodoForm(request.POST, instance=todo)
        if todo.is_valid():
            todo.save()
            messages.success(request, 'the todo messages was updated successfully')
            return redirect('home')
        return render(request, 'main/todo.html', {"form":todo})
    return render(request, 'main/todo.html', {'form':TodoForm(instance=todo)})

todos/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} | Super Todos {% endblock title%}</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home'%}">Wobble</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">detail</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo' %}">Todos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Login</a>

            </li>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container">
      {% if messages  %}
        {% for message in messages  %}
        <div class="alert alert-{{message.tags}}" role="alert">
          {{ message }}
          </div>
        {% endfor %}
      {% endif %}

    {% block body_block %}
    {% endblock %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
      integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
      crossorigin="anonymous"></script>
    <script src="{% static "js/gijgo.min.js" %}" charset="utf-8"></script>
    <script type="text/javascript">
       $('#id_due_date').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
    </script>
  </body>
</html>

todos/main/templates/main/contact.html
{% extends 'main/base.html'%}


{% block body_block %}
{% endblock %}

todos/main/templates/main/detail.html
{% extends 'main/base.html' %}

{% block title%} details {{ block.super }}{% endblock title%}
{% block body_block %}
  <div class="container">
    <div class="card text-center mt-2">
      <div class="card-header">
        {{ todo.title}}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ todo.due_date}}</h5>
        <p class="card-text">{{ todo.description }}.</p>
        <a href="{% url 'home' %}" class="btn btn-primary">Back</a>
      </div>
      <div class="card-footer text-muted">
        {% if not todo.done %}
          <p>Not done yet</p>
        {% else %}
          <p>Done</p>
        {%endif%}
      </div>
    </div>
  </div>



{% endblock %}

todos/main/templates/main/home.html
{% extends 'main/base.html'%}

{% block title %} Home {{ block.super }}{% endblock title %}
{% block body_block %}
{# <div class="container"> #}
  <h4>Today is {{ today }}</h4>
  <p>{{ app_name }}</p>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Title</th>
        <th scope="col">Due date</th>
        <th scope="col">Done</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      {% for todo in todos %}
        {% if todo.done %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'update' pk=todo.pk %}">{{todo.title}}</a></td>
            <td>{{ todo.due_date}}</td>
            <td>{{ todo.done|yesno:'Yes,No' }}</td>
            <td>{{ todo.description|truncatewords:5}}</td>
            <td><a class='btn btn-primary' href="{% url 'detail' pk=todo.pk %}">Show</a></td>
          </tr>

        {% else %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <!-- <td>{{todo.title}}</td> -->
            <td><a href="{% url 'update' pk=todo.pk %}">{{todo.title}}</a></td>
          <td>{{ todo.due_date}}</td>
          <td>{{ todo.done|yesno:"Yes,No" }}</td>
          <td>{{ todo.description|truncatewords:5}}</td>
          <td><a class='btn btn-primary' href="{% url 'detail' pk=todo.pk %}">Show</a></td>
        </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
{# </div> #}



{% endblock %}

todos/main/templates/main/todo.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block title%}Todo{{block.super}}{% endblock title%}

{% block body_block %}

    <form class="" action="" method="POST">
      {% csrf_token %}
      {{ form|crispy }}

      <button class='btn btn-primary' type="submit" name="button">Submit</button>
    </form>



{% endblock %}